"use client";

import "./globals.css";
import Header from "./components/header";
import Footer from "./components/footer";
import React, { useState } from "react";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isopen, setIsOpen] = useState(false);
  const [isDarkMode, setIsDarkMode] = useState(false);

  const toggleDarkMode = () => {
    setIsDarkMode(!isDarkMode);
    if (isDarkMode) {
      document.documentElement.classList.remove("dark");
    } else {
      document.documentElement.classList.add("dark");
    }
    console.log(isDarkMode);
  };

  return (
    <html lang="en" className={isDarkMode ? "dark" : ""}>
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdn.jsdelivr.net/gh/devicons/devicon@latest/devicon.min.css"
        />
      </head>
      <body className="dark:bg-black min-h-screen">
        <Header
          isOpen={isopen}
          setIsOpen={setIsOpen}
          isDarkMode={isDarkMode}
          toggleDarkMode={toggleDarkMode}
        />
        <main
          className={`transition-all duration-300 ${isopen ? "blur-lg" : ""}`}
        >
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
